groups:
- name: HighTraffic
  rules:
  - alert: HighTraffic
    expr: rate(http_requests_total[1m]) > 10
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: High traffic detected
      description: This alert fires to confirm the settings of the test
