name: JMeter Load Test

on:
  schedule:
    # Schedule to run at 5 AM UTC
    - cron: '0 5 * * *'

jobs:
  loadTest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Run JMeter test
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
        tar -xzf apache-jmeter-5.4.1.tgz
        ./apache-jmeter-5.4.1/bin/jmeter -n -t ./path/to/your/testplan.jmx -l ./results.jtl
